import os
from config import supabase

def create_tables():
    print("hz Hazırlanıyor: weekly_fixtures tablosu...")
    
    # SQL sorgusu
    # Supabase Python client doğrudan DDL çalıştırmayı (rpc harici) bazen kısıtlayabilir 
    # ama SQL editörden yapılmış varsayıyoruz.
    # Ancak burada kullanıcı bizden bunu python ile yapmamızı istedi.
    # Supabase-py 'postgrest' client'ı doğrudan CREATE TABLE desteklemez.
    # Bu yüzden RPC (Remote Procedure Call) kullanmak gerekir YA DA
    # Kullanıcıya SQL'i verip çalıştırmasını istemek daha güvenlidir.
    # Ancak "match_queue" ve diğerleri script ile oluşturulmadıysa, muhtemelen SQL Editor kullanıldı.
    
    # B PLANI: Kullanıcıya bu tabloyu oluşturması gerektiğini bildireceğiz veya
    # var olan tabloların üzerine yazıyor gibi davranacağız.
    # FAKAT, user request'e göre kod yazmalıyız.
    # Eğer postgres connection string varsa psycopg2 ile yapabiliriz ama yok.
    
    # Basit bir kontrol yapalım: Tabloya erişmeye çalışalım.
    try:
        supabase.table("weekly_fixtures").select("id").limit(1).execute()
        print("✅ Tablo zaten mevcut: weekly_fixtures")
    except Exception as e:
        print(f"⚠️ Tablo yok veya erişilemiyor: {e}")
        print("⚠️ Lütfen Supabase SQL Editöründe şu komutu çalıştırın:\n")
        print("""
CREATE TABLE IF NOT EXISTS weekly_fixtures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_code VARCHAR(50) UNIQUE,
    home_team VARCHAR(100),
    away_team VARCHAR(100),
    league VARCHAR(100),
    season VARCHAR(50),
    match_date TIMESTAMP,
    score_ft VARCHAR(20),
    score_ht VARCHAR(20),
    status VARCHAR(20),
    ms_1 FLOAT, ms_x FLOAT, ms_2 FLOAT,
    cs_1x FLOAT, cs_12 FLOAT, cs_x2 FLOAT,
    iyms_11 FLOAT, iyms_1x FLOAT, iyms_12 FLOAT,
    iyms_x1 FLOAT, iyms_xx FLOAT, iyms_x2 FLOAT,
    iyms_21 FLOAT, iyms_2x FLOAT, iyms_22 FLOAT,
    au_15_alt FLOAT, au_15_ust FLOAT,
    au_25_alt FLOAT, au_25_ust FLOAT,
    kg_var FLOAT, kg_yok FLOAT,
    tg_0_1 FLOAT, tg_2_3 FLOAT, tg_4_5 FLOAT, tg_6_plus FLOAT,
    created_at TIMESTAMP DEFAULT NOW()
);
        """)

if __name__ == "__main__":
    create_tables()
