"""
Lig isimlerini normalize eden script.

Kullanım:
  python scripts/normalize_leagues.py          # Dry-run (sadece göster)
  python scripts/normalize_leagues.py --apply  # DB'ye yaz

Bu script:
1. matches tablosundaki tüm distinct league isimlerini çeker
2. Normalize kurallarını uygular (sponsor, yıl, tur temizleme + ülke çıkarma)
3. league_mappings tablosunu günceller
4. matches tablosundaki league_display kolonunu günceller

İlk çalıştırmadan önce Supabase SQL Editor'de çalıştırın:
  ALTER TABLE matches ADD COLUMN IF NOT EXISTS league_display VARCHAR(200);
  ALTER TABLE matches ADD COLUMN IF NOT EXISTS league_country VARCHAR(100);

  CREATE TABLE IF NOT EXISTS league_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_name VARCHAR(200) UNIQUE NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    country VARCHAR(100),
    tier INT DEFAULT 99,
    created_at TIMESTAMP DEFAULT NOW()
  );
"""

import re
import sys
import os

# Projenin root dizinine config.py'yi import edebilmek için path ekle
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from config import supabase

# ─── MANUAL OVERRIDES ───
# Tam eşleşme ile öncelikli kontrol. Regex'e düşmeden temiz isim ata.
MANUAL_MAP = {
    # raw_name: (display_name, country, tier)
    # Türkiye
    "Türkiye Trendyol Süper Lig":       ("Süper Lig", "Türkiye", 1),
    "Türkiye Trendyol 1. Lig":          ("1. Lig", "Türkiye", 2),
    "Türkiye Nesine 2.Lig Beyaz Grup":  ("2. Lig", "Türkiye", 3),
    "Türkiye Kadınlar Süper Lig":       ("Kadınlar Süper Lig", "Türkiye", 1),
    # İngiltere
    "İngiltere Premier Lig":            ("Premier Lig", "İngiltere", 1),
    "İngiltere Premier Lig 2":          ("Premier Lig 2", "İngiltere", 2),
    "İngiltere Championship":           ("Championship", "İngiltere", 2),
    "İngiltere Championship Kadınlar":  ("Championship Kadınlar", "İngiltere", 2),
    "İngiltere 1.Lig":                  ("League One", "İngiltere", 3),
    "İngiltere Professional Development Lig": ("Professional Development Lig", "İngiltere", 4),
    # İtalya
    "İtalya Serie A":                   ("Serie A", "İtalya", 1),
    "İtalya Serie B":                   ("Serie B", "İtalya", 2),
    "İtalya Kadınlar Serie A":          ("Kadınlar Serie A", "İtalya", 1),
    "İtalya Primavera Şampiyonası 1":   ("Primavera 1", "İtalya", 3),
    # Fransa
    "Fransa Ligue 1":                   ("Ligue 1", "Fransa", 1),
    # Hollanda
    "Hollanda Eredivisie":              ("Eredivisie", "Hollanda", 1),
    "Hollanda Eerste Divisie":          ("Eerste Divisie", "Hollanda", 2),
    "Hollanda Kadınlar Eredivisie":     ("Kadınlar Eredivisie", "Hollanda", 1),
    # Belçika
    "Belçika Pro Lig":                  ("Pro Lig", "Belçika", 1),
    "Belçika 1.Lig A":                  ("1. Lig A", "Belçika", 2),
    "Belçika Challenger Pro Lig":       ("Challenger Pro Lig", "Belçika", 2),
    "Belçika Kadınlar 1.Lig":           ("Kadınlar 1. Lig", "Belçika", 1),
    # Portekiz
    "Portekiz Premier Lig":             ("Primeira Liga", "Portekiz", 1),
    # Polonya
    "Polonya Ekstraklasa":              ("Ekstraklasa", "Polonya", 1),
    "Polonya 1.Lig":                    ("1. Lig", "Polonya", 2),
    "Polonya 2.Lig":                    ("2. Lig", "Polonya", 3),
    # Rusya
    "Rusya Premier Lig":                ("Premier Lig", "Rusya", 1),
    "Rusya FNL":                        ("FNL", "Rusya", 2),
    # Sırbistan
    "Sırbistan Süper Lig":              ("Süper Lig", "Sırbistan", 1),
    "Sırbistan 1.Lig":                  ("1. Lig", "Sırbistan", 2),
    # Hırvatistan
    "Hırvatistan 1.HNL":               ("1. HNL", "Hırvatistan", 1),
    # İskoçya
    "İskoçya Premiership":              ("Premiership", "İskoçya", 1),
    # Yunanistan
    "Yunanistan Süper Lig":             ("Süper Lig", "Yunanistan", 1),
    # Danimarka
    "Danimarka 1.Lig":                  ("1. Lig", "Danimarka", 2),
    # Ukrayna
    "Ukrayna Premier Lig":              ("Premier Lig", "Ukrayna", 1),
    # Romanya
    "Romanya 1.Lig":                    ("Liga I", "Romanya", 1),
    "Romanya 2.Lig":                    ("Liga II", "Romanya", 2),
    # Slovenya
    "Slovenya 1.SNL":                   ("1. SNL", "Slovenya", 1),
    # Bulgaristan
    "Bulgaristan 1.Lig":               ("1. Lig", "Bulgaristan", 1),
    # Azerbaycan
    "Azerbaycan Premier Lig":           ("Premier Lig", "Azerbaycan", 1),
    "Azerbaycan 1.Lig":                 ("1. Lig", "Azerbaycan", 2),
    # Avusturya
    "Avusturya 1.Lig":                  ("1. Lig", "Avusturya", 2),
    # Mısır
    "Mısır Premier Lig":                ("Premier Lig", "Mısır", 1),
    "Mısır 2. Lig":                     ("2. Lig", "Mısır", 2),
    # Suudi Arabistan
    "Suudi Arabistan Pro Lig":          ("Pro Lig", "Suudi Arabistan", 1),
    "Suudi Arabistan 1.Lig":            ("1. Lig", "Suudi Arabistan", 2),
    # Kuzey İrlanda
    "Kuzey İrlanda Premiership":        ("Premiership", "Kuzey İrlanda", 1),
    "Kuzey İrlanda Championship":       ("Championship", "Kuzey İrlanda", 2),
    # Uluslararası
    "Hazırlık Kulüpler":                ("Hazırlık Maçları", "Uluslararası", 99),
}

# ─── KNOWN COUNTRIES (prefix → country) ───
# Lig isminin başında ülke adı varsa çıkar.
KNOWN_COUNTRIES = [
    # Multi-word countries first (longer names match first)
    "Birleşik Arap Emirlikleri",
    "Kuzey İrlanda",
    "Güney Afrika",
    "Güney Kore",
    "Kuzey Makedonya",
    "Suudi Arabistan",
    "Sierra Leone",
    "Burkina Faso",
    "Kosta Rika",
    "Copa Libertadores",
    "Copa Sudamericana",
    "El Salvador",
    "Faroe Adaları",
    # International organizations
    "Avrupa",
    "AFC",
    "CAF",
    "CONCACAF",
    "UEFA",
    # Countries
    "ABD",
    "Almanya",
    "Andorra",
    "Angola",
    "Arjantin",
    "Arnavutluk",
    "Avustralya",
    "Avusturya",
    "Azerbaycan",
    "Bahreyn",
    "Bangladeş",
    "Belçika",
    "Bolivya",
    "Bosna-Hersek",
    "Botsvana",
    "Brezilya",
    "Bulgaristan",
    "Burundi",
    "Cebelitarık",
    "Cezayir",
    "Danimarka",
    "Ekvador",
    "Endonezya",
    "Ermenistan",
    "Estonya",
    "Etiyopya",
    "Fas",
    "Filipinler",
    "Finlandiya",
    "Fransa",
    "Galler",
    "Gana",
    "Guatemala",
    "Gürcistan",
    "Hindistan",
    "Hollanda",
    "Honduras",
    "Hırvatistan",
    "Irak",
    "Japonya",
    "Kanada",
    "Katar",
    "Kenya",
    "Kolombiya",
    "Letonya",
    "Litvanya",
    "Lüksemburg",
    "Macaristan",
    "Malezya",
    "Mali",
    "Malta",
    "Meksika",
    "Moldova",
    "Moğolistan",
    "Myanmar",
    "Mısır",
    "Nijerya",
    "Norveç",
    "Pakistan",
    "Paraguay",
    "Peru",
    "Polonya",
    "Portekiz",
    "Romanya",
    "Rusya",
    "Seyşeller",
    "Singapur",
    "Slovenya",
    "Slovakya",
    "Sırbistan",
    "Tayland",
    "Tanzanya",
    "Tunus",
    "Türkiye",
    "Uganda",
    "Ukrayna",
    "Umman",
    "Uruguay",
    "Venezuela",
    "Vietnam",
    "Yunanistan",
    "Zambiya",
    "Özbekistan",
    "Ürdün",
    "İngiltere",
    "İran",
    "İrlanda",
    "İskoçya",
    "İspanya",
    "İsrail",
    "İsveç",
    "İsviçre",
    "İtalya",
]

# Uzun ülke adları önce eşleşsin
KNOWN_COUNTRIES.sort(key=len, reverse=True)

# ─── COUNTRY PRIORITY ───
COUNTRY_PRIORITY = {
    "Türkiye": 1,
    "UEFA": 2,
    "İngiltere": 3,
    "İspanya": 4,
    "İtalya": 5,
    "Almanya": 6,
    "Fransa": 7,
    "Hollanda": 8,
    "Portekiz": 9,
    "Belçika": 10,
    "İskoçya": 11,
    "Rusya": 12,
    "Polonya": 13,
    "Yunanistan": 14,
    "Hırvatistan": 15,
    "Romanya": 16,
    "Sırbistan": 17,
    "Danimarka": 18,
    "Norveç": 19,
    "İsveç": 20,
    "İsviçre": 21,
    "Avusturya": 22,
    "Ukrayna": 23,
    "Slovenya": 24,
    "Bulgaristan": 25,
    "Azerbaycan": 26,
    "Gürcistan": 27,
    "Kuzey İrlanda": 28,
    "Arnavutluk": 29,
    "ABD": 40,
    "CONCACAF": 50,
    "Copa Libertadores": 51,
    "Copa Sudamericana": 51,
    "AFC": 52,
    "CAF": 52,
    "Brezilya": 53,
    "Arjantin": 54,
    "Meksika": 55,
    "Almanya": 6,
    "Avustralya": 70,
    "Suudi Arabistan": 60,
    "Mısır": 61,
    "Uluslararası": 99,
}


def extract_country(raw):
    """Lig isminden ülke adını çıkar. (country, remaining) döner."""
    for country in KNOWN_COUNTRIES:
        if raw.startswith(country + " "):
            remaining = raw[len(country):].strip()
            return country, remaining
        if raw == country:
            return country, ""
    return "", raw


def clean_display_name(name):
    """Display name'den yıl, tur ve gereksiz bilgileri temizle."""
    # Sondaki yıl bilgisini sil: "Serie A 2026" → "Serie A"
    name = re.sub(r'\s+20\d{2}$', '', name)
    # Aşama bilgisini temizle: "1. Aşama", "1.Aşama"
    name = re.sub(r'\s+\d+\.\s*[Aa]şama$', '', name)
    # Tur bilgisini sadeleştir ama turu koru (bilgi kaybı olmasın)
    # "Son 16 Turu" → "Son 16", "Çeyrek Final" kalır, "3.Tur" → "3. Tur"
    name = re.sub(r'\s+Turu$', '', name)
    # Boşluk temizle
    name = name.strip()
    return name


def normalize_league(raw_name):
    """
    Raw lig ismini normalize et.
    Returns: (display_name, country, tier)
    """
    raw = raw_name.strip()

    # 1. Manuel eşleşme
    if raw in MANUAL_MAP:
        return MANUAL_MAP[raw]

    # 2. Ülke çıkar
    country, remaining = extract_country(raw)

    # 3. Display name temizle
    display = clean_display_name(remaining) if remaining else raw

    # Eğer ülke bulunamadıysa display raw'ın kendisi olsun
    if not country:
        display = clean_display_name(raw)
        country = "Diğer"

    # 4. Tier tahmini (basit)
    tier = 99
    lower = display.lower()
    if any(k in lower for k in ["süper", "premier", "serie a", "ligue 1", "eredivisie", "pro lig", "ekstraklasa", "1.hnl", "1. snl"]):
        tier = 1
    elif any(k in lower for k in ["championship", "serie b", "1.lig", "1. lig", "eerste", "fnl", "2.lig", "liga ii"]):
        tier = 2
    elif any(k in lower for k in ["şampiyonlar ligi", "avrupa ligi", "konferans ligi", "libertadores", "challenge"]):
        tier = 1  # Uluslararası kupalar

    return display, country, tier


def fetch_distinct_leagues():
    """DB'den tüm distinct league isimlerini çek."""
    all_leagues = set()
    offset = 0
    batch = 1000

    while True:
        resp = (
            supabase.table("matches")
            .select("league")
            .neq("league", None)
            .limit(batch)
            .range(offset, offset + batch - 1)
            .execute()
        )

        if not resp.data:
            break
        for row in resp.data:
            if row.get("league"):
                all_leagues.add(row["league"])
        if len(resp.data) < batch:
            break
        offset += batch

    return sorted(all_leagues)


def upsert_mappings(mappings):
    """league_mappings tablosuna upsert."""
    for m in mappings:
        supabase.table("league_mappings").upsert(m, on_conflict="raw_name").execute()


def update_matches_batch(raw_name, display_name, country):
    """Belirli bir raw league'e sahip tüm maçları güncelle."""
    # Supabase batch update
    resp = (
        supabase.table("matches")
        .update({"league_display": display_name, "league_country": country})
        .eq("league", raw_name)
        .execute()
    )
    return len(resp.data) if resp.data else 0


def main():
    apply = "--apply" in sys.argv

    print("📊 Lig isimlerini normalize ediliyor...\n")

    raw_leagues = fetch_distinct_leagues()
    print(f"Toplam {len(raw_leagues)} farklı lig ismi bulundu.\n")

    mappings = []
    for raw in raw_leagues:
        display, country, tier = normalize_league(raw)
        priority = COUNTRY_PRIORITY.get(country, 90)
        mappings.append({
            "raw_name": raw,
            "display_name": display,
            "country": country,
            "tier": tier,
        })
        flag = "✅" if raw in MANUAL_MAP else "🔄"
        print(f"  {flag} [{country:.<20s}] {raw}")
        print(f"     → {display}  (tier={tier}, priority={priority})")

    if not apply:
        print(f"\n⚠️  Dry-run modu. Değişiklik yapılmadı.")
        print(f"    Uygulamak için: python scripts/normalize_leagues.py --apply")
        print(f"\n📋 Önce Supabase SQL Editor'de şu komutları çalıştırın:")
        print(f"    ALTER TABLE matches ADD COLUMN IF NOT EXISTS league_display VARCHAR(200);")
        print(f"    ALTER TABLE matches ADD COLUMN IF NOT EXISTS league_country VARCHAR(100);")
        print(f"    CREATE TABLE IF NOT EXISTS league_mappings (")
        print(f"      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,")
        print(f"      raw_name VARCHAR(200) UNIQUE NOT NULL,")
        print(f"      display_name VARCHAR(200) NOT NULL,")
        print(f"      country VARCHAR(100),")
        print(f"      tier INT DEFAULT 99,")
        print(f"      created_at TIMESTAMP DEFAULT NOW()")
        print(f"    );")
        return

    print(f"\n🔧 league_mappings tablosuna yazılıyor...")
    upsert_mappings(mappings)
    print(f"   ✅ {len(mappings)} mapping yazıldı.")

    print(f"\n🔧 matches tablosu güncelleniyor...")
    total_updated = 0
    for m in mappings:
        count = update_matches_batch(m["raw_name"], m["display_name"], m["country"])
        total_updated += count
        if count > 0:
            print(f"   {m['raw_name']} → {count} maç güncellendi")

    print(f"\n✅ Toplam {total_updated} maç güncellendi.")


if __name__ == "__main__":
    main()
