-- daily_picks: Günlük kupon snapshot'ları
-- Her gün 17:00'da generate-daily-picks komutu ile oluşturulur.
-- 2 güvenli kupon: safe_1 (top 3) + safe_2 (sonraki 3)

CREATE TABLE IF NOT EXISTS daily_picks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Kimlik
  pick_date DATE NOT NULL,
  coupon_type VARCHAR(10) NOT NULL,           -- 'safe_1' | 'safe_2'

  -- Pick'ler (3 adet, JSONB dizisi)
  picks JSONB NOT NULL,
  combined_odds FLOAT NOT NULL,               -- 3 oranın çarpımı
  avg_wilson FLOAT NOT NULL,                  -- Ortalama wilson_lower
  avg_ev FLOAT NOT NULL,                      -- Ortalama EV

  -- Sonuçlar (maçlar bittikten sonra güncellenir)
  results JSONB,
  is_settled BOOLEAN DEFAULT FALSE,
  hits_count INT,                             -- 0-3 arası
  coupon_hit BOOLEAN,                         -- 3/3 mü?

  -- Meta
  generated_at TIMESTAMP DEFAULT NOW(),
  settled_at TIMESTAMP,

  -- Günde 2 güvenli kupon
  UNIQUE(pick_date, coupon_type)
);

-- Backtest sorguları için indeksler
CREATE INDEX IF NOT EXISTS idx_daily_picks_date ON daily_picks(pick_date DESC);
CREATE INDEX IF NOT EXISTS idx_daily_picks_settled ON daily_picks(is_settled) WHERE is_settled = TRUE;
