-- Maç İstatistikleri (sadece oynanmış maçlar için dolar)
CREATE TABLE IF NOT EXISTS match_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_code VARCHAR(50) UNIQUE NOT NULL REFERENCES matches(match_code),
  shots_home INT,
  shots_away INT,
  shots_on_home INT,
  shots_on_away INT,
  corners_home INT,
  corners_away INT,
  possession_home FLOAT,
  possession_away FLOAT,
  fouls_home INT,
  fouls_away INT,
  offsides_home INT,
  offsides_away INT,
  scraped_at TIMESTAMP DEFAULT NOW()
);

-- Head2Head / Form / Puan Durumu
CREATE TABLE IF NOT EXISTS match_h2h (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_code VARCHAR(50) UNIQUE NOT NULL REFERENCES matches(match_code),
  form_home VARCHAR(10),
  form_away VARCHAR(10),
  standing_home INT,
  standing_away INT,
  points_home INT,
  points_away INT,
  tg_dist_home JSONB,
  tg_dist_away JSONB,
  kg_pct_home FLOAT,
  kg_pct_away FLOAT,
  au25_over_pct_home FLOAT,
  au25_over_pct_away FLOAT,
  scorers_home JSONB,
  scorers_away JSONB,
  referee_stats JSONB,
  h2h_total JSONB,
  scraped_at TIMESTAMP DEFAULT NOW()
);
