-- backtest_picks: Günün Önerileri algoritmasının geçmiş performans verileri
-- Her satır = bir pick önerisi + gerçek sonucu

CREATE TABLE IF NOT EXISTS backtest_picks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id UUID NOT NULL,
  pick_date DATE NOT NULL,
  match_id BIGINT NOT NULL,
  match_code VARCHAR(20),
  home_team VARCHAR(100) NOT NULL,
  away_team VARCHAR(100) NOT NULL,
  league VARCHAR(200),
  match_date TIMESTAMP NOT NULL,
  outcome_key VARCHAR(20) NOT NULL,
  outcome_label VARCHAR(30) NOT NULL,
  category_label VARCHAR(20) NOT NULL,
  odds_value FLOAT NOT NULL,
  wilson_lower FLOAT NOT NULL,
  hit_rate FLOAT NOT NULL,
  total_similar INT NOT NULL,
  hit_count INT NOT NULL,
  ev FLOAT NOT NULL,
  implied_prob FLOAT NOT NULL,
  score_ft VARCHAR(10),
  score_ht VARCHAR(10),
  is_hit BOOLEAN,
  is_settled BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_backtest_picks_date ON backtest_picks(pick_date DESC);
CREATE INDEX IF NOT EXISTS idx_backtest_picks_date_settled ON backtest_picks(pick_date DESC, is_settled);
CREATE INDEX IF NOT EXISTS idx_backtest_picks_category ON backtest_picks(category_label);
CREATE INDEX IF NOT EXISTS idx_backtest_picks_run ON backtest_picks(run_id);
